### ISSUE TITLE
FOG preprocessing

### ISSUE THREAD

**Issue by MohammadBelalIrshaid** [BenjaminFiltjens/MS-GCN#10]
Greetings, I am using read_frame.py to develop my preprocessed FOG dataset (I took FOG dataset from an external source that contains 4 tasks as text files). I tried running the code so I can reproduce the input and output, but it gives me an error in **line 17 in read_frame.py** where it cannot read the dataset.

I changed my text file to csv and c3d but none of them worked for me, may you assist me in this? And does read_frame.py work with datasets in the form of .txt?

**Comment by BenjaminFiltjens** [comment]
Hi, read_frame is only for c3d files. It will save standardized .c3d files exported by commercial MoCap systems as a .csv of format TxNC. These are then processed in data_gen to CxTxNxM (see manuscript for info). The order may differ in the manuscript and M is not mentioned since we only consider 1 subject so M=1.

Either way, we do not provide support for preprocessing proprietary datasets. From the provided public datasets, gen_data.py, and the problem statement in the manuscript you can infer the required data format for preprocessing your data.
