### ISSUE TITLE
About read_frame.py files

### ISSUE THREAD

**Issue by Forgetmmmm** [BenjaminFiltjens/MS-GCN#7]
Hello,I would like to ask if the input of read_frame.py file is the video, and the output is the joint data of the people in the video. What does the first dimension 6 of the downloaded feature file represent?

**Comment by BenjaminFiltjens** [comment]
Hi, 
As datasets typically come in different formats, we provide just a rough example of data preprocessing. The assumptions for the provided example are mentioned in the readme (i.e., input is a c3d format). We use c3d in our example because it is a common and standardized data format common in biomechanics, whereas for video there are already many useful repositories (e.g., you can get inspiration from mmskeleton (https://github.com/open-mmlab/mmskeleton)). Roughly, the preprocessing for video will be:
- Pre-process the video with a pose estimator
- Save poses for a video in the format T, N*C (where T is time, N are the number of joints, and C are the number of features per joint)
- Process the poses with gendata.py, which will generate a npy file with shape C,T,N,1 (see line 34 in read_skeleton.py). 1 because we assume that there is only 1 person. In the example C=3.

Now you also know what the first dimension is: we use 6 features per node for all datasets.
